In [2]:
import pandas as pd
import numpy as np

Esercizio 1: leggo il file excel in una matrice numpy

In [6]:
patterns_excel = pd.read_excel('PCA-Data-Esercise.xlsx') #reading the file
matrix = patterns_excel.to_numpy() #converting to numpy matrix

X = matrix[2:, 3:]
X

array([[ 8.9 ,  9.4 ,  7.5 ,  2.3 ,  7.4 ,  1.5 , 10.5 ],
       [ 7.99, 10.3 ,  0.4 ,  9.7 ,  8.9 ,  6.5 ,  1.3 ],
       [ 8.01, 10.56,  1.6 , 10.02,  7.59,  7.01,  1.68],
       [ 9.06,  6.25,  7.09,  2.3 ,  4.5 ,  1.33,  8.45],
       [ 6.75,  7.88,  6.22,  8.42,  6.04,  6.99,  6.05],
       [ 6.99,  7.56,  6.78,  3.01,  7.85,  3.14,  4.25],
       [ 8.33,  8.01,  2.52,  3.5 ,  6.55,  2.47,  6.7 ],
       [ 5.95,  7.73,  3.5 ,  5.8 ,  6.45,  3.2 ,  2.4 ],
       [ 7.23,  8.21,  3.56,  1.5 ,  3.24,  4.01,  5.63],
       [ 8.68,  9.04,  4.56,  4.36,  8.25,  2.32,  6.78],
       [ 9.12,  7.56,  6.89,  1.23,  5.89,  2.32,  7.88],
       [ 7.56,  6.12,  6.52,  4.56,  6.01,  1.25,  6.12],
       [ 6.22,  8.44,  1.01,  2.14,  7.13,  4.22,  1.23],
       [ 8.14,  7.06,  2.1 ,  6.55,  4.12,  0.88,  2.26],
       [ 7.99,  7.12,  5.98,  5.45,  5.01,  1.08,  4.16],
       [ 6.04,  6.42,  3.01,  5.02,  3.01,  6.89,  3.01]])

2. Calcolo la matrice di correlazione del set di dati

In [13]:
corr_matrix = np.corrcoef(X, rowvar=False) #computing correlation matrix
corr_matrix

array([[ 1.        ,  0.16757524,  0.33766416, -0.16911178,  0.16985897,
        -0.50027743,  0.61121332],
       [ 0.16757524,  1.        , -0.44850911,  0.40845869,  0.68981876,
         0.44297767, -0.19854519],
       [ 0.33766416, -0.44850911,  1.        , -0.45542002, -0.11154095,
        -0.48616688,  0.78726824],
       [-0.16911178,  0.40845869, -0.45542002,  1.        ,  0.27640542,
         0.5708486 , -0.56884819],
       [ 0.16985897,  0.68981876, -0.11154095,  0.27640542,  1.        ,
         0.12893455, -0.07102122],
       [-0.50027743,  0.44297767, -0.48616688,  0.5708486 ,  0.12893455,
         1.        , -0.48913824],
       [ 0.61121332, -0.19854519,  0.78726824, -0.56884819, -0.07102122,
        -0.48913824,  1.        ]])

3. Diagonalizzo la matrice di correlazione

In [14]:
eigenvalues, eigenvectors = np.linalg.eig(corr_matrix) #computing eigenvalues and eigenvectors

D = np.diag(eigenvalues) #diagonal matrix
Q = eigenvectors #orthonormal matrix
print("Autovalori: ", eigenvalues)
print("Autovettori: ", eigenvectors)
print(Q)

Autovalori:  [3.2779843  1.76783943 0.08594353 0.1146129  0.49122574 0.66503414
 0.59735996]
Autovettori:  [[-0.27941646 -0.51506523 -0.31596012 -0.38203377  0.18585213 -0.34410162
   0.50784517]
 [ 0.32522314 -0.5438888  -0.16902175  0.63953301  0.37695193 -0.00325081
  -0.13689678]
 [-0.45079054 -0.07725518 -0.51311928  0.23763271 -0.3289439   0.59941175
   0.05966822]
 [ 0.41674005 -0.0980413   0.26969437  0.18909308 -0.44562083  0.14249813
   0.69952894]
 [ 0.18934637 -0.5910749   0.12115845 -0.38547333 -0.4750204   0.10813988
  -0.46278586]
 [ 0.43528356  0.06653997 -0.17472425 -0.45035286  0.44856947  0.60086751
   0.10246   ]
 [-0.46254529 -0.26365739  0.70026171  0.0376144   0.29954175  0.35950987
   0.07604421]]
[[-0.27941646 -0.51506523 -0.31596012 -0.38203377  0.18585213 -0.34410162
   0.50784517]
 [ 0.32522314 -0.5438888  -0.16902175  0.63953301  0.37695193 -0.00325081
  -0.13689678]
 [-0.45079054 -0.07725518 -0.51311928  0.23763271 -0.3289439   0.59941175
   0.05966822]
 [

4. Ordino in modo decrescente gli autovalori e gli autovettori corrispondenti

In [21]:
idx = np.argsort(eigenvalues)[::-1]
eigenvalues_desc = eigenvalues[idx]
eigenvectors_desc = eigenvectors[:,idx]
D_desc = np.diag(eigenvalues_desc)

print("D decrescente:\n", D_desc)
print("Q decrescente:\n", eigenvectors_desc)



D decrescente:
 [[3.2779843  0.         0.         0.         0.         0.
  0.        ]
 [0.         1.76783943 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.66503414 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.59735996 0.         0.
  0.        ]
 [0.         0.         0.         0.         0.49122574 0.
  0.        ]
 [0.         0.         0.         0.         0.         0.1146129
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.08594353]]
Q decrescente:
 [[-0.27941646 -0.51506523 -0.34410162  0.50784517  0.18585213 -0.38203377
  -0.31596012]
 [ 0.32522314 -0.5438888  -0.00325081 -0.13689678  0.37695193  0.63953301
  -0.16902175]
 [-0.45079054 -0.07725518  0.59941175  0.05966822 -0.3289439   0.23763271
  -0.51311928]
 [ 0.41674005 -0.0980413   0.14249813  0.69952894 -0.44562083  0.18909308
   0.26969437]
 [ 0.18934637 -0.5910749   0.10813988 -0.46278586 -0.4750204  -0.38547333
   0.1211584

5. Scelgo quanti autovalori considerare nella PCA

In [17]:
total_var = np.sum(eigenvalues_desc)
cum_perc = np.cumsum(eigenvalues_desc) / total_var

print("Peso cumulativo (%):", cum_perc)

Peso cumulativo (%): [0.46828347 0.72083196 0.81583684 0.90117398 0.97134908 0.98772235
 1.        ]


6. PCA: moltiplico i dati iniziali per gli autovettori degli autovalori scelti

In [20]:
k = 2
P = eigenvectors_desc[:, :k]

X_reduced = np.dot(X, P)
X_reduced

array([[ -4.654773  , -17.54409098],
       [  8.89254002, -15.87013993],
       [  8.36210154, -15.43787806],
       [ -5.21399323, -13.63827401],
       [  2.76961646, -13.76867422],
       [ -0.40906455, -14.08254605],
       [ -0.1835881 , -14.65856163],
       [  3.1948551 , -12.34021415],
       [ -0.57496397, -11.74398754],
       [ -0.28802761, -16.67685692],
       [ -4.20269667, -14.86675184],
       [ -2.30954357, -13.25603309],
       [  4.06144368, -12.33982725],
       [  1.92241677, -11.80943143],
       [ -0.84689979, -12.97040733],
       [  3.31218764,  -9.44174929]])

Esercizio 2: rifaccio analogamente per il secondo set di dati

In [26]:
df = pd.read_excel('PCA-Data-Esercise.xlsx', sheet_name=1)

matrixY = df.to_numpy()

Y = matrixY[2:, 3:]
print(Y)

[[ 0.1 33.  11.   0.   0.1  0.1]
 [ 0.1  3.   3.   0.   0.1  0. ]
 [ 7.  19.  19.   4.   7.   1. ]
 [18.   3.  28.  19.  12.   6. ]
 [ 5.   7.  28.   3.  10.   1. ]
 [11.   9.  33.   7.  10.   6. ]
 [ 8.  13.  33.   6.  15.  15. ]
 [18.   5.  33.   4.  19.  12. ]
 [ 6.   6.  38.   3.  10.   6. ]]


In [27]:
corr_matrixY = np.corrcoef(Y, rowvar=False) #computing correlation matrix
corr_matrixY

array([[ 1.        , -0.47142657,  0.6309353 ,  0.74997535,  0.82359404,
         0.6152573 ],
       [-0.47142657,  1.        , -0.3603326 , -0.37681965, -0.45997879,
        -0.28663979],
       [ 0.6309353 , -0.3603326 ,  1.        ,  0.39645634,  0.84664349,
         0.69439662],
       [ 0.74997535, -0.37681965,  0.39645634,  1.        ,  0.44580084,
         0.31777439],
       [ 0.82359404, -0.45997879,  0.84664349,  0.44580084,  1.        ,
         0.8441605 ],
       [ 0.6152573 , -0.28663979,  0.69439662,  0.31777439,  0.8441605 ,
         1.        ]])

In [29]:
eigenvaluesY, eigenvectorsY = np.linalg.eig(corr_matrixY) #computing eigenvalues and eigenvectors

Dy = np.diag(eigenvaluesY) #diagonal matrix
Qy = eigenvectors #orthonormal matrix
print("Autovalori: ", eigenvaluesY)
print("Autovettori: ", eigenvectorsY)

Autovalori:  [3.85798046 0.93663779 0.67502915 0.03437055 0.19203762 0.30394443]
Autovettori:  [[-0.46006111  0.22118363 -0.2498484   0.4884065  -0.64107623  0.16576405]
 [ 0.29373329 -0.47263609 -0.82077191 -0.04922742 -0.10578058 -0.05528543]
 [-0.42880439 -0.31772881  0.04360025  0.26172418  0.17804833 -0.78299007]
 [-0.33999909  0.59905749 -0.50838938 -0.22846818  0.46003144 -0.05695914]
 [-0.48184777 -0.25190585  0.05954661 -0.7651246  -0.33770538  0.03687524]
 [-0.41281311 -0.45212265 -0.0016447   0.23004965  0.46952815  0.59311738]]


In [31]:
idx = np.argsort(eigenvaluesY)[::-1]
eigenvalues_descY = eigenvaluesY[idx]
eigenvectors_descY = eigenvectorsY[:,idx]
D_descY = np.diag(eigenvalues_descY)

print("D decrescente:\n", D_descY)
print("Q decrescente:\n", eigenvectors_descY)

D decrescente:
 [[3.85798046 0.         0.         0.         0.         0.        ]
 [0.         0.93663779 0.         0.         0.         0.        ]
 [0.         0.         0.67502915 0.         0.         0.        ]
 [0.         0.         0.         0.30394443 0.         0.        ]
 [0.         0.         0.         0.         0.19203762 0.        ]
 [0.         0.         0.         0.         0.         0.03437055]]
Q decrescente:
 [[-0.46006111  0.22118363 -0.2498484   0.16576405 -0.64107623  0.4884065 ]
 [ 0.29373329 -0.47263609 -0.82077191 -0.05528543 -0.10578058 -0.04922742]
 [-0.42880439 -0.31772881  0.04360025 -0.78299007  0.17804833  0.26172418]
 [-0.33999909  0.59905749 -0.50838938 -0.05695914  0.46003144 -0.22846818]
 [-0.48184777 -0.25190585  0.05954661  0.03687524 -0.33770538 -0.7651246 ]
 [-0.41281311 -0.45212265 -0.0016447   0.59311738  0.46952815  0.23004965]]


In [32]:
total_var = np.sum(eigenvalues_descY)
cum_perc = np.cumsum(eigenvalues_descY) / total_var

print("Peso cumulativo (%):", cum_perc)

Peso cumulativo (%): [0.64299674 0.79910304 0.9116079  0.96226531 0.99427157 1.        ]


In [33]:
k = 3
Py = eigenvectors_descY[:, :k]

Y_reduced = np.dot(Y, Py)
Y_reduced

array([[  4.8408779 , -19.1402925 , -26.62506505],
       [ -0.49940421,  -2.37416694,  -2.35054517],
       [-10.93252274, -13.2878815 , -18.13357632],
       [-34.12545789,  -0.68652358, -14.69348695],
       [-18.50198372, -12.27295003,  -6.70518513],
       [-26.2429677 , -13.34414779, -11.6695991 ],
       [-29.47240895, -21.82593365, -13.41182143],
       [-36.43183997, -16.68237909,  -8.08423077],
       [-25.6078876 , -17.01703169,  -5.70648263]])